Login/register forms, Creating users, started auth
laslorajda/grupna-praksa-maj-2024 pull request #20
Opened 2024-05-17 13:22 UTC by Bat0oo

I did login/register forms, started users controller and authentication, routes, navbar
Didn't have time to finish it all, but wanted to commit it so it can be reviewed

2024-05-17 17:28 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Features/Users/CreateUser.cs
> +        private readonly IRepository<User> _userRepository;
Oh no. We don't need any of this. Only Novalite employees will be using this, and we have different ways of keeping track of them

2024-05-17 17:29 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Program.cs
> +builder.Configuration.AddJsonFile("appsettings.json");
What is this for?

2024-05-17 17:29 UTC, laslorajda commented on Konteh/Konteh.FrontOfficeApi/Konteh.FrontOfficeApi.csproj
> +    <PackageReference Include="Microsoft.Identity.Client" Version="4.61.0" />
Not sure why this package was added here.

2024-05-17 17:30 UTC, laslorajda commented on Konteh/Konteh.FrontOfficeApi/appsettings.json
> +  "AllowedHosts": "*",
Frontoffice will not be using EntraID, remove this please

2024-05-17 17:30 UTC, laslorajda commented on Konteh/Konteh.Infrastructure/Migrations/20240517115523_AddedUsers.cs
> +#nullable disable
remove this migration

2024-05-17 17:30 UTC, laslorajda commented on Konteh/Konteh.Infrastructure/Migrations/20240517115523_AddedUsers.cs
> +#nullable disable
google how to do that via the CLI

2024-05-17 17:31 UTC, laslorajda commented on back-office-app/src/app/app-routing.module.ts
> +  {path: 'register',component:RegisterComponent},
We won't have any registration

2024-05-17 17:32 UTC, laslorajda commented on back-office-app/src/app/config.service.ts
> +export class ConfigService {
I thought we moved this to environment files?

2024-05-17 17:32 UTC, laslorajda commented on back-office-app/src/custom-theme.scss
> +// Include the common styles for Angular Material. We include this here so that you only
the what?

2024-05-17 17:33 UTC, laslorajda commented on back-office-app/src/app/app.component.ts
> +  navigateToForm2() {
what does any of this do?

2024-05-17 18:37 UTC, laslorajda commented on back-office-app/src/app/navbar/navbar.component.html
> +    <button mat-button (click)="navigateTo('')">Home</button>
Just tested these buttons, they work perfectly fine.

2024-05-17 18:38 UTC, laslorajda commented on back-office-app/src/app/login/login.component.html
> +  <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
noooo, just use the default Microsoft stuff, all this work was unnecessary. In the future if you are unsure about what to do, please ask.

2024-05-21 12:03 UTC, irenva101 commented on Konteh/Konteh.BackOfficeApi/Controllers/QuestionsController.cs
> +
delete spacing please

2024-05-21 12:05 UTC, irenva101 approved these changes

2024-05-21 12:16 UTC, laslorajda requested changes

2024-05-21 12:16 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Controllers/QuestionsController.cs
> +            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
what is this for?

2024-05-21 12:16 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Controllers/QuestionsController.cs
> +            return StatusCode(500, $"Erorr occurred while processing your request {ex}");
I don't see what value this adds

2024-05-21 12:16 UTC, laslorajda commented on Konteh/Konteh.BackOfficeApi/Konteh.BackOfficeApi.csproj
> +    <PackageReference Include="Microsoft.Identity.Client" Version="4.61.0" />
you don't need this dependency

2024-05-21 12:16 UTC, laslorajda commented on Konteh/Konteh.Domain/Konteh.Domain.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.5" />
Why are these dependencies in the domain project?!

2024-05-21 12:16 UTC, laslorajda commented on Konteh/Konteh.FrontOfficeApi/Program.cs
> +app.UseAuthentication();
you can probably remove these from FrontOffice

2024-05-21 12:16 UTC, laslorajda commented on Konteh/Konteh.Infrastructure/Konteh.Infrastructure.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.5" />
These packages do not belong here.

2024-05-21 12:16 UTC, laslorajda commented on back-office-app/src/app/app.component.ts
> +    this.msalBroadcastService.msalSubject$
please delete all of this, I'm pretty sure it's unused

2024-05-21 12:16 UTC, laslorajda commented on back-office-app/src/app/auth.service.ts
> +export class AuthService {
I'm not sure you need this service?

2024-05-21 12:16 UTC, laslorajda commented on back-office-app/src/app/navbar/navbar.component.html
> +    <button mat-button (click)="test123()">Test123</button>
please delete this, it was used for testing

2024-05-21 12:16 UTC, laslorajda commented on back-office-app/src/app/navbar/navbar.component.ts
> +  private idTokenKey='idToken';
What does this do?

2024-05-21 12:16 UTC, laslorajda commented on back-office-app/src/app/navbar/navbar.component.ts
> +        console.log(response.account);
no console logs please

2024-05-21 12:16 UTC, laslorajda commented on back-office-app/src/app/navbar/navbar.component.ts
> +    this.authService.handleRedirectObservable()
pretty sure you can get rid of all of this.

2024-05-21 12:16 UTC, laslorajda commented on back-office-app/src/environments/environment.development.ts
> +  ]
formatting

2024-05-21 12:57 UTC, laslorajda approved these changes

2024-05-21 12:57 UTC, merged